server {
    server_name _;
    listen 8080 default_server;

    charset utf-8;
    root /usr/share/nginx;
    index index.html;

    location /quizz {
        try_files $uri $uri/ /quizz/index.html;
    }
}
